// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi8z7veACgrnEBDbwvlAoWVrVHoEa6pZ0',
    appId: '1:497006982683:web:3237fe8fbe9cd9689a2abe',
    messagingSenderId: '497006982683',
    projectId: 'chat-app-69973',
    authDomain: 'chat-app-69973.firebaseapp.com',
    storageBucket: 'chat-app-69973.firebasestorage.app',
    measurementId: 'G-04VKXY2X33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPir_NST4GqZkh9aiMchp_sky0GjqaTgM',
    appId: '1:497006982683:android:49d227aa32aa4d849a2abe',
    messagingSenderId: '497006982683',
    projectId: 'chat-app-69973',
    storageBucket: 'chat-app-69973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3e4dT2RAWUXfNcEcy8XebXw1cn1XNylo',
    appId: '1:497006982683:ios:6119dbda6a10ed069a2abe',
    messagingSenderId: '497006982683',
    projectId: 'chat-app-69973',
    storageBucket: 'chat-app-69973.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3e4dT2RAWUXfNcEcy8XebXw1cn1XNylo',
    appId: '1:497006982683:ios:6119dbda6a10ed069a2abe',
    messagingSenderId: '497006982683',
    projectId: 'chat-app-69973',
    storageBucket: 'chat-app-69973.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi8z7veACgrnEBDbwvlAoWVrVHoEa6pZ0',
    appId: '1:497006982683:web:13e5248f78c887159a2abe',
    messagingSenderId: '497006982683',
    projectId: 'chat-app-69973',
    authDomain: 'chat-app-69973.firebaseapp.com',
    storageBucket: 'chat-app-69973.firebasestorage.app',
    measurementId: 'G-PVJZ627P8V',
  );

}